"""second migration

Revision ID: 626a909545d3
Revises: 835fffe8b903
Create Date: 2021-09-01 21:31:06.481012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '626a909545d3'
down_revision = '835fffe8b903'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('car',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('make', sa.String(length=100), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('color', sa.String(length=100), nullable=True),
    sa.Column('year', sa.Numeric(precision=4), nullable=True),
    sa.Column('max_speed', sa.String(length=100), nullable=True),
    sa.Column('miles_per_gallon', sa.String(length=150), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('user_token', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_token'], ['user.token'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('car')
    # ### end Alembic commands ###
